In [6]:
import numpy as np

# Basic array operation without Numpy

In [11]:
a= [i for i in range(10)]
b= [i for i in range(10, 20)]
c=[]

for i in range(len(a)):
  c.append(a[i]+b[i])

print(c)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


# Array Addition

In [12]:
a= np.arange(10)
b= np.arange(10, 20)

c= a+b
print(c)

[10 12 14 16 18 20 22 24 26 28]


# Array Creation

In [10]:
#using array:
arr1= np.array([1,2,3,4,5])
print(arr1)

#using arange:
start= 1
end= 10
arr= np.arange(start, end)
print(arr)

#using linspace
arr2= np.linspace(1,2,4)
print(arr2)

#using zeros
arr3= np.zeros((2,3), dtype=int)
print(arr3)


[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]
[1.         1.33333333 1.66666667 2.        ]
[[0 0 0]
 [0 0 0]]


# Reshape - Flatten - Ravel

In [15]:
#reshape
arr= np.array([1,2,3,4,5,6])
rarr= arr.reshape(2,3)
print(rarr)

#flatten
farr= rarr.flatten()
print(farr)

#ravel
rrarr= rarr.ravel()
print(rrarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Array Slicing

In [16]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:])
print(arr[0:1])
print(arr[0:1,2])
print(arr[0:2,1:2])
print(arr[0:3:2,0:3:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[3]
[[2]
 [5]]
[[1 3]
 [7 9]]


# Broadcasting

In [17]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
arr3= np.array([[2],[3],[4]])
print(arr1+arr2)
print(arr1+arr3)
arr4= np.array([1,2,3,4])
# arr1+arr4 #error

[5 7 9]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


# Eye

In [18]:
np.eye(3)
np.eye(2,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

# Random

In [26]:

# 1. Uniform random floats: rand() → values between 0 and 1
print("1D rand():", np.random.rand(3))
print("2D rand():\n", np.random.rand(2, 2))
print("-" * 40)

# 2. Standard normal distribution: randn()
print("1D randn():", np.random.randn(3))
print("2D randn():\n", np.random.randn(2, 2))
print("-" * 40)

# 3. Random integers in a range: randint(low, high, size)
print("1D randint(10, 20, 3):", np.random.randint(10, 20, 3))
print("2D randint(10, 20, (2,3)):\n", np.random.randint(10, 20, (2, 3)))
print("-" * 40)

# 4. Random choice from array: choice(array)
arr = np.array([1, 2, 3, 4, 5])
print("Random choice (single):", np.random.choice(arr))
print("Random choice (size=2):", np.random.choice(arr, size=2))
print("Random choice without replacement [0,1,2]:", np.random.choice(3, size=3, replace=False))
print("-" * 40)

# 5. Shuffle array in-place: shuffle(arr)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:", arr)
print("-" * 40)

# 6. Set seed for reproducibility: seed()
np.random.seed(42)
print("Seeded rand(3):", np.random.rand(3))


1D rand(): [0.59865848 0.15601864 0.15599452]
2D rand():
 [[0.05808361 0.86617615]
 [0.60111501 0.70807258]]
----------------------------------------
1D randn(): [-0.46947439  0.54256004 -0.46341769]
2D randn():
 [[-0.46572975  0.24196227]
 [-1.91328024 -1.72491783]]
----------------------------------------
1D randint(10, 20, 3): [19 12 16]
2D randint(10, 20, (2,3)):
 [[13 18 12]
 [14 12 16]]
----------------------------------------
Random choice (single): 5
Random choice (size=2): [1 2]
Random choice without replacement [0,1,2]: [2 1 0]
----------------------------------------
Shuffled array: [3 4 1 5 2]
----------------------------------------
Seeded rand(3): [0.37454012 0.95071431 0.73199394]


# Math

In [25]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))           # 15
print("Mean:", np.mean(arr))         # 3.0
print("Standard Deviation:", np.std(arr))  # ~1.41
print("Variance:", np.var(arr))      # 2.0
print("Min:", np.min(arr))           # 1
print("Max:", np.max(arr))           # 5
print("Median:", np.median(arr))     # 3.0

print("Exp:", np.exp([1, 2]))         # [2.71 7.38]
print("Natural Log:", np.log([1, np.e]))  # [0. 1.]
print("Log base 10:", np.log10([10, 100]))  # [1. 2.]
print("Power:", np.power([2, 3], 2))  # [4 9]
print("Square Root:", np.sqrt([4, 9, 16]))  # [2. 3. 4.]

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Median: 3.0
Exp: [2.71828183 7.3890561 ]
Natural Log: [0. 1.]
Log base 10: [1. 2.]
Power: [4 9]
Square Root: [2. 3. 4.]


In [28]:
!git add .
!git commit -m "numpy added"
!git branch -M code
!git push -u origin code

[code 9147f0a] numpy added
 3 files changed, 861 insertions(+), 32 deletions(-)
 create mode 100644 .ipynb_checkpoints/numpy-checkpoint.ipynb
 create mode 100644 numpy.ipynb


To https://github.com/Harimhs/ML-Learning.git
 ! [rejected]        code -> code (fetch first)
error: failed to push some refs to 'https://github.com/Harimhs/ML-Learning.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


In [29]:
!git pull

Merge made by the 'ort' strategy.
 README.md | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)


From https://github.com/Harimhs/ML-Learning
   bdb5c1d..150cf33  code       -> origin/code
